language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

jobs:
  include:
    - stage: style checks
      rvm: 2.4
      before_install:
        - gem install rubocop
      script:
        - rubocop

  allow_failures:
    - stage: style checks

before_install:
  - gem update bundler
