# currently supported rubies: https://www.ruby-lang.org/en/downloads/branches/

language: ruby

rvm:
  - 1.9.3
  - 2.2
  - 2.3
  - 2.4
  - ruby-head

jobs:
  include:
    - stage: style checks
      rvm: 2.4
      before_install:
        - gem install rubocop
      script:
        - rubocop

  allow_failures:
    - stage: style checks
    - rvm: ruby-head

before_install:
  - gem update bundler
